name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0+80332226"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "7b82a9c9c72836b95b36d456ecc4521b30bf09cf"
url = "git+file:/tmp/tmpmhtu1q0x/publish__submit-request-cancel/hello_upstream"

