name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0+85042307"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "1f72a2645df2152126e07e4e69cbf1e8d76dbff4"
url = "git+file:/tmp/tmprzgcjbrx/publish__submit-request-cancel/hello_upstream"

