name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-87762059+autotest_by_mosteo@kukumo"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "f3c79e87eefcbe83bc8b0c290fd3e71be6b15d96"
url = "git+file:/tmp/tmpwyfprb46/publish__submit-request-cancel/hello_upstream"

