name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-61321127+autotest_by_mosteo@zelda"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "1ce17ed71ae4e19cd2675e8b4828024b67c5b31c"
url = "git+file:/tmp/tmp5nrz8ce5/publish__submit-request-cancel/hello_upstream"

