name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-33622493+autotest_by_mosteo@zelda"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "4e90aa6e7bf24919eb70b02aa1b9ed94e3bf08ba"
url = "git+file:/tmp/tmpb5juhjac/publish__submit-request-cancel/hello_upstream"

