name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-91003666+autotest_by_mosteo@kukumo"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "c23de42f5fc17d75abda3676aba6b4e0a3bc1c9d"
url = "git+file:/tmp/tmptain_8yj/publish__submit-request-cancel/hello_upstream"

