name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-15759441+autotest_by_mosteo@kukumo"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "950176adabc9f988e6c1cc330fefeba82fe70663"
url = "git+file:/tmp/tmpwyfprb46/publish__submit-request-cancel/hello_upstream"

