name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-28777894+autotest_by_mosteo@kukumo"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "32f19c4c49574e59c398a8f4234abad88b7b92f4"
url = "git+file:/tmp/tmphh2zo_t7/publish__submit-request-cancel/hello_upstream"

